echo 'package main'
echo ''
echo 'import ('
echo '    "fmt"'
echo '    "net/http"'
echo '    "strings"'
echo ')'
echo ''
echo 'func '$1' (w http.ResponseWriter, r *http.Request) {'
echo '    w.Header().Set("Content-Type", "'$3'; charset=utf-8")'
echo '    if strings.Contains(r.UserAgent(),"Windows") {'
echo '        return'
echo '    }'
echo '    fmt.Fprintf(w,"%s", `'
cat "$2"
echo ''
echo '     `)'
echo '}'
